services:
  nginx:
    image: openresty/openresty:alpine
    container_name: enroll-nginx
    ports:
      - "8088:8088"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/mime.types:/usr/local/openresty/nginx/conf/mime.types:ro
      - ./config:/srv/config:ro
      - ./enroll:/enroll
    restart: unless-stopped
