{{- if or .Values.matomo.envCm .Values.global.envCm -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "helper.fullname" . }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "matomo")) | nindent 4 }}
data:
  {{- if .Values.global.envCm -}}
  {{- include "helper.env" .Values.global.envCm | indent 2 }}
  {{- end -}}
  {{- if .Values.matomo.envCm -}}
  {{- include "helper.env" .Values.matomo.envCm | indent 2 }}
  {{- end -}}
{{- end -}}
