{{- if not .Values.matomo.statefulset }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helper.fullname" . }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "matomo")) | nindent 4 }}
spec:
  replicas: {{ .Values.matomo.replicaCount }}
  revisionHistoryLimit: {{ .Values.matomo.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "matomo") | nindent 6 }}
  strategy:
    type: {{ .Values.matomo.strategy.type }}
    {{- if eq .Values.matomo.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.matomo.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.matomo.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      {{- if or .Values.matomo.podAnnotations .Values.matomo.secrets .Values.matomo.env .Values.global.env .Values.global.secrets }}
      annotations:
        {{- include "helper.checksum" (list $ "/configmap.yaml") | nindent 8 }}
        {{- include "helper.checksum" (list $ "/secret.yaml") | nindent 8 }}
        {{- if .Values.matomo.podAnnotations }}
        {{- toYaml .Values.matomo.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels: {{- include "helper.labels" (dict "root" . "componentName" "matomo") | nindent 8 }}
        {{- if .Values.matomo.podLabels }}
        {{- toYaml .Values.matomo.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.matomo.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.matomo.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (get .Values "matomo").serviceAccount.enabled }}
      serviceAccountName: {{ .Values.matomo.serviceAccount.name | default (include "helper.fullname" .) }}
      {{- end }}
      {{- if .Values.matomo.podSecurityContext }}
      securityContext: {{- toYaml .Values.matomo.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.matomo.initContainers }}
      initContainers: {{- tpl (toYaml .Values.matomo.initContainers) . | nindent 6 }}
      {{- end }}
      containers:
      - name: matomo
        {{- if .Values.matomo.securityContext }}
        securityContext: {{- toYaml .Values.matomo.securityContext | nindent 10 }}
        {{- end }}
        image: "{{ .Values.matomo.image.repository }}:{{ .Values.matomo.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.matomo.image.pullPolicy }}
        {{- if .Values.matomo.command }}
        command:
        {{- range .Values.matomo.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.matomo.args }}
        args:
        {{- range .Values.matomo.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.matomo.containerPort }}
          name: {{ .Values.matomo.containerPortName | default "http" }}
          protocol: TCP
        {{- if .Values.matomo.extraPorts }}
          {{- toYaml .Values.matomo.extraPorts | nindent 8 }}
        {{- end }}
        {{- if or .Values.matomo.envCm .Values.global.envCm .Values.matomo.envSecret .Values.global.envSecret .Values.matomo.envFrom }}
        envFrom:
        {{- if or .Values.matomo.envCm .Values.global.envCm }}
        - configMapRef:
            name: {{ include "helper.fullname" . }}
        {{- end }}
        {{- if or .Values.matomo.envSecret .Values.global.envSecret }}
        - secretRef:
            name: {{ include "helper.fullname" . }}
        {{- end }}
        {{- if .Values.matomo.envFrom }}
          {{- toYaml .Values.matomo.envFrom | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.matomo.env }}
        env: {{- include "helper.env.map-to-array" .Values.matomo.env | nindent 8 }}
        {{- end -}}
        {{- if .Values.matomo.probes.startupProbe }}
        startupProbe: {{- toYaml .Values.matomo.probes.startupProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.matomo.probes.readinessProbe }}
        readinessProbe: {{- toYaml .Values.matomo.probes.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.matomo.probes.livenessProbe }}
        livenessProbe: {{- toYaml .Values.matomo.probes.livenessProbe | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.matomo.resources | nindent 10 }}
        {{- if .Values.matomo.volumeMounts }}
        volumeMounts: {{- toYaml .Values.matomo.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.matomo.extraContainers }}
        {{- tpl (toYaml .Values.matomo.extraContainers) . | nindent 6 }}
      {{- end }}
      {{- if .Values.matomo.hostAliases }}
      hostAliases: {{- toYaml .Values.matomo.hostAliases | nindent 6 }}
      {{- end }}
      {{- if .Values.matomo.nodeSelector }}
      nodeSelector: {{- toYaml .Values.matomo.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.matomo.affinity }}
      affinity: {{- toYaml .Values.matomo.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.matomo.tolerations }}
      tolerations: {{- toYaml .Values.matomo.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.matomo.volumes }}
      volumes: {{- toYaml .Values.matomo.volumes | nindent 6 }}
      {{- end }}
{{- end }}
