{{- if .Values.matomo.ingress.enabled -}}
{{- $fullNameApp := include "helper.fullname" . -}}
{{- $svcPortApp := .Values.matomo.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullNameApp }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "matomo")) | nindent 4 }}
  {{- if .Values.matomo.ingress.labels }}
    {{- toYaml .Values.matomo.ingress.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.matomo.ingress.annotations }}
  annotations:
    {{- tpl (toYaml .Values.matomo.ingress.annotations) . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.matomo.ingress.className }}
  ingressClassName: {{ .Values.matomo.ingress.className }}
  {{- end }}
  {{- if gt (len .Values.matomo.ingress.tls) 0 }}
  tls:
  {{- range .Values.matomo.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName | quote | default (printf "%s-%s" $fullNameApp "tls") }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.matomo.ingress.hosts }}
  - host: {{ .name | quote }}
    http:
      paths:
      - path: {{ .path | default "/" }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
          {{- if .backend }}
            name: {{ .backend.serviceName | default $fullNameApp }}
            port:
              number: {{ .backend.portNumber | default $svcPortApp }}
          {{- else }}
            name: {{ $fullNameApp }}
            port:
              number: 80
          {{- end }}
  {{- end }}
{{- end }}
