apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: device-management-route
  namespace: bootstrap
spec:
  hostnames:
    - onyxia.gpu.minint.fr
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: api-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: device-management
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /bootstrap
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      timeouts:
        request: 300s
    - backendRefs:
        - group: ""
          kind: Service
          name: adminer
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /adminer
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      timeouts:
        request: 300s
    - backendRefs:
        - group: ""
          kind: Service
          name: filebrowser
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /files
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      timeouts:
        request: 300s
