apiVersion: v1
kind: Service
metadata:
  name: device-management
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "device-management.name" . }}
    app.kubernetes.io/component: app
