{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "device-management.fullname" . }}-config
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Values.config.configJson | indent 4 }}
{{- end }}
