{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "device-management.fullname" . }}
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
{{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
{{- if .Values.ingress.hosts }}
{{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ default (include "device-management.fullname" $) $.Values.ingress.service.name }}
                port:
                  number: {{ default $.Values.service.port $.Values.ingress.service.port }}
{{- end }}
{{- end }}
{{- else if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ default (include "device-management.fullname" .) .Values.ingress.service.name }}
                port:
                  number: {{ default .Values.service.port .Values.ingress.service.port }}
{{- end }}
{{- if .Values.ingress.tlsList }}
  tls:
{{- range .Values.ingress.tlsList }}
    - secretName: {{ .secretName }}
      hosts:
{{- range .hosts }}
        - {{ . }}
{{- end }}
{{- end }}
{{- else if and .Values.ingress.tls.enabled .Values.ingress.host }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.host }}
{{- end }}
{{- end }}
