apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: device-management-dgx
  namespace: argocd
spec:
  project: default
  source:
    # Update repoURL/targetRevision according to your Git repository.
    repoURL: https://github.com/REPLACE_ME/device-management.git
    targetRevision: main
    path: deploy-dgx
  destination:
    server: https://kubernetes.default.svc
    namespace: bootstrap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
